print('welcome to bunnycraft. © 2013 cbroc inc.')
print('type bunny name to create a character.')
print('bunny names: thumper, flopsy, cotton tail, toodles, and fluffy.')
thumper = ('hello thumper.')
flopsy = ('hello flopsy.')
cottontail = ('hello cotton tail.')
flopsy = ('hello flopsy')
print('type newbunny for a new bunny')
newbunny = ('type thumper, flopsy, cotton tail, or fluffy.')
print('type bunny to get a bunny.')
bunny = ('type mchoppy, momey, or cotton.')
mchoppy = ('you got a red bunny.')
momey = ('you got a brown bunny.')
cotton = ('you got a white bunny.')
fluffy = ('hello fluffy')
print('type delete(bunnyname) to delete a bunny')
deletethumper = ('deleted.')
deleteflopsy = ('deleted.')
deletecottontail = ('deleted.')
deleteflopsy = ('deleted.')
deletefluffy = ('deleted.')
deletemchoppy = ('deleted.')
deletemomey = ('deleted.')
deletecotton = ('deleted.')
print('type multiplayer to play with friends.')
multiplayer = ('type player2 to create a new player.')
player2 = ('addded player2. player2, create a  bunny.')
toodles = ('hello toodles')
