from tkinter import *
tk = Tk()
canvas = Canvas(tk, width=500, height=500)
canvas.pack()
c = colorchooser.askcolor()
c2 = colorchooser.askcolor()
b1 = canvas.create_oval(20, 20, 40, 40, fill=c[1])
tk.title('Bunny Craft')
b2 = canvas.create_oval(30, 25, 40, 35, fill='black')
b3 = canvas.create_oval(30, 20, 20, 35, fill=c[1])
b4 = canvas.create_oval(20, 20, 40, 40, fill=c2[1])
b5 = canvas.create_oval(30, 25, 40, 35, fill='black')
b6 = canvas.create_oval(30, 20, 20, 35, fill=c2[1])
def moveb1(event):
    tk.update()
    canvas.move(b1, 3, 0)
    canvas.move(b2, 3, 0)
    canvas.move(b3, 3, 0)
canvas.bind_all('<KeyPress-1>', moveb1)
def moveb2(event):
    tk.update()
    canvas.move(b1, -3, 0)
    canvas.move(b2, -3, 0)
    canvas.move(b3, -3, 0)
canvas.bind_all('<KeyPress-2>', moveb2)
def moveb3(event):
    tk.update()
    canvas.move(b1, 0, -3)
    canvas.move(b2, 0, -3)
    canvas.move(b3, 0, -3)
canvas.bind_all('<KeyPress-3>', moveb3)
def moveb4(event):
    tk.update()
    canvas.move(b1, 0, 3)
    canvas.move(b2, 0, 3)
    canvas.move(b3, 0, 3)
canvas.bind_all('<KeyPress-4>', moveb4)
def moveb5(event):
    tk.update()
    canvas.move(b4, 3, 0)
    canvas.move(b5, 3, 0)
    canvas.move(b6, 3, 0)
canvas.bind_all('<KeyPress-5>', moveb5)
def moveb6(event):
    tk.update()
    canvas.move(b4, -3, 0)
    canvas.move(b5, -3, 0)
    canvas.move(b6, -3, 0)
canvas.bind_all('<KeyPress-6>', moveb6)
def moveb7(event):
    tk.update()
    canvas.move(b4, 0, -3)
    canvas.move(b5, 0, -3)
    canvas.move(b6, 0, -3)
canvas.bind_all('<KeyPress-7>', moveb7)
def moveb8(event):
    tk.update()
    canvas.move(b4, 0, 3)
    canvas.move(b5, 0, 3)
    canvas.move(b6, 0, 3)
canvas.bind_all('<KeyPress-8>', moveb8)

