print('welcome to ∑PSILON. © copyright 2013 cbroc inc.')
import time
print('loading...')
time.sleep(10)
print('importing...')
time.sleep(10)
print('updating...')
time.sleep(5)
print('complete!')
print('3')
time.sleep(3)
print('2')
time.sleep(3)
print('1')
time.sleep(3)
print('begin')
import turtle
wn = turtle.Screen()
t = turtle.Turtle()
def forward(size):
    t.forward(size)
    pass
def backward(size):
    t.backward(size)
    pass
def up(size):
    t.left(90)
    t.forward(size)
    t.right(90)
    pass
def down(size):
    t.right(90)
    t.forward(size)
    t.left(90)
    pass
a = turtle.Turtle()
a.right(90)
a.forward(100)
a.right(90)
a.forward(100)
a.backward(200)
a.left(45)
a.right(45)
a.backward(300)
a.left(67)
a.right(34)
a.forward(80)
a.backward(20)
a.left(67)
a.forward(82)
a.right(23)
a.backward(100)
b = turtle.Turtle()
b.left(80)
b.forward(70)
b.right(35)
b.backward(56)
b.forward(80)
b.left(43)
b.forward(37)
b.right(87)
b.backward(67)
b.left(150)
b.forward(34)
